### ISSUE TITLE
AD Connect Pre-Req

### ISSUE THREAD

**Issue by robc8119** [stgeorgi/wvdquickstart#1]
It seems the "devOpsSetupRunbook" is contingent on the "WVDTestUsers" group being present for it to be successful. In my existing test AD environment, AD Connect is not syncing everything in the directory, so it couldn't find WVDTestUsers after the next sync and the runbook eventually fails on this step. Something to check if you're trying to use this deployment with your own AD environment. Maybe tweak the pre-req for people using existing AD/ADConnect configurations? Awesome, great work!

**Comment by samvdjagt** [comment]
Thanks for the feedback! Will include this in the "known limitations" section on the QuickStart website (under Troubleshoot)
