### ISSUE TITLE
Code:InvalidTemplate

### ISSUE THREAD

**Issue by cloudman10** [stgeorgi/wvdquickstart#2]
Hi there,
When deploying a template, I am getting an error of (Code:InvalidTemplate) as you can see below,

Any thoughts on this?

Error type
Deployment template validation failed: 'The template resource '/userCreation' for type 'Microsoft.Compute/virtualMachines/extensions' at line '1' and column '857' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'. (Code: InvalidTemplate)

Regards,

**Comment by justin-shiah** [comment]
@cloudman10 Do you still need help on this issue?

**Comment by cloudman10** [comment]
Since then, I stopped deploying a template, yes, it will be great if you can share the solution you have.

**Comment by justin-shiah** [comment]
Were you deploying with an empty or existing subscription? Did you make any customizations at all?

**Comment by bonJoeV** [comment]
I had a similar issue:

Deployment template validation failed: 'The template resource '/userCreation' for type 'Microsoft.Compute/virtualMachines/extensions' at line '1' and column '890' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.

Deploying into an existing subscription with a new Resource group, new Vnet (DNS and peering configured to talk to my AD controllers vnet).

**Comment by justin-shiah** [comment]
Thanks for the feedback - I'll go ahead and file a bug for this.
