### ISSUE TITLE
Variable not found. 

### ISSUE THREAD

**Issue by ecarrascom** [stgeorgi/wvdquickstart#20]
Hi,

I get an error when the wizzard is launched:

Get-AutomationVariable : Variable not found. To create this Variable, navigate to the Variables blade and create a Variable named: principalId. Refer doc for more details (https://docs.microsoft.com/en-us/azure/automation/shared-resources/variables#create-and-get-a-variable) At line:25 char:16 + $principalId = Get-AutomationVariable -Name 'principalId' + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (:) [Get-AutomationVariable], AssetManagementClientException + FullyQualifiedErrorId : 3,Orchestrator.AssetManagement.Cmdlets.GetAutomationVariableCmdlet

Get-AutomationVariable : Variable not found. To create this Variable, navigate to the Variables blade and create a Variable named: ObjectId. Refer doc for more details (https://docs.microsoft.com/en-us/azure/automation/shared-resources/variables#create-and-get-a-variable) At line:34 char:13 + $ObjectId = Get-AutomationVariable -Name 'ObjectId' + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (:) [Get-AutomationVariable], AssetManagementClientException + FullyQualifiedErrorId : 3,Orchestrator.AssetManagement.Cmdlets.GetAutomationVariableCmdlet

thx
regards

**Comment by stgeorgi** [comment]
Which wizard is this?
