### ISSUE TITLE
WVD QuickStart Deployment failing in UK South Region.

### ISSUE THREAD

**Issue by ash0ka** [stgeorgi/wvdquickstart#22]
Has anyone managed to successfully complete the WVD quickstart template 'til the end in the UK South region?

Creating the Active Directory, Virtual Network, and AD Connector on the Domain Controller all works smoothly.  However, when in comes to clicking on the link to Deploy to Azure, the first template to create the Automation Account and runbooks, I'm getting an error half-way through.  The Automation account seems to be created along with various runbooks.  But when it comes to creating a job, the template bombs out and fails to complete the rest of the deployment.

I've attached 3 screen shots:  the first shows how far it gets before failing and the other screenshots shows details of the error, but I can't make sense out of them.  

I've been at this for a couple of days.  It's supposed to be simple, but when it goes wrong it's very difficult to figure out where it's going wrong.  Anyone one whose completed this in UK South, I'd welcome a pointer to see where I may be going wrong.  I'm pretty sure the Azure environment is ok.  It's getting stuck on some resource not in a state to be provisioned with necessary priviledges, but I don't know how to debug this...

Any help would be greatly appreciated
![WVD - QuickStart - Deploy to Azure Template - Deployment  Failed - Screenshot 1](https://user-images.githubusercontent.com/57270337/101552756-4e40ea00-39ab-11eb-9a6e-8d415c1bce1a.PNG)
![WVD - QuickStart - Deploy to Azure Template - Deployment  Failed - Screenshot 2](https://user-images.githubusercontent.com/57270337/101552759-4ed98080-39ab-11eb-93a8-05e8ff94ab43.PNG)
![WVD - QuickStart - Deploy to Azure Template - Deployment  Failed - Screenshot 3](https://user-images.githubusercontent.com/57270337/101552760-4ed98080-39ab-11eb-9073-96efe197205d.PNG)

**Comment by silversmurfer** [comment]
seeing the same

**Comment by mes007** [comment]
For the time being WVD only supports certain US based regions for its metadata. WVD QuickStart does not have separate parameters for metadata and session host locations as is the case when you manually first create host pool into certain region and then deploy session hosts to the same or e.g. Europe based region. Try with e.g. East US.

**Comment by ash0ka** [comment]
Thanks mes007.  Being UK based and my customer/prospect base too, we need to get these scripts working for Europe based regions.  If we need to specify separate parameters for metadata and session host locations, is there a way to get this request to the WVD dev team and get it onto their dev to do list as a matter of urgency.  These scripts are a great aid to simplifying the whole deployment process, especially for SMEs and CSPs who aren't yet experts or experienced in Azure.

**Comment by ash0ka** [comment]
Actually, I would go further and classify this as a bug that needs fixing by the wvd team who wrote the QuickStart as it is intended for global use.  Pretty please....

**Comment by stgeorgi** [comment]
@ash0ka I recommend looking through the official documentation and educate yourself of the features WVD offers. We do not offer data stored outside of US. This has been something we have clearly stated and document for almost 2 years. And a further closer look at the WVD roadmap will show when we are planning to add the support additional regions.

**Comment by ash0ka** [comment]
OK.  I understand your position stgeorgi.  I have looked through the official documentation and the features WVD offers.  It's fine.  However, it's the devops automation runbook code that I am not familiar with, and don't have the time or skill to delve deeper into.  I can manually setup the WVD environment with no issues, without needing to run the wvdQuickStart.  I was just excited that this would be a time saver for us, but am a little disappointed that it is not fully supported outside the US.  I'll keep to the manual process for now, and will check the roadmap from time to time.   BTW the wvdquickstart is being promoted worldwide, and the link for raising issues points to here.

**Comment by ash0ka** [comment]
From the roadmap:

Windows Virtual Desktop: choose the EU geography to store the Windows Virtual Desktop service metadata: planned for March 2021

Windows Virtual Desktop allows customers to pick the region best-suited to them to deploy their VMs. They should also get the choice of storing the service metadata in the geography best suited for their needs.

Feature ID: 59889
Added to Roadmap: 9/22/2020
Last Modified: 11/4/2020
Tags: General Availability, Worldwide (Standard Multi-Tenant), Windows Virtual Desktop

**Comment by stgeorgi** [comment]
@ash0ka once WVD team announce geo distributed data it will be a minor fix in WVDQuickstart to support it. TY for your understanding.

**Comment by mes007** [comment]
@stgeorgi While waiting for global metadata availability I'd assume it being not such a big change on WVD Quickstart to have a parameter for specifying VM region - for someone who knows the process :)

**Comment by stgeorgi** [comment]
@mes007 not something we want to support at the moment. I often get asked to add this and that input field...the goal of WVD quickstart is to be a quick start least possible amount of options to confuse users. Advanced user are expected to be more ... savvy and figure out the somewhat minor changes like changing region for the hostpool
