### ISSUE TITLE
FSLogix wont mount - Enable AD DS

### ISSUE THREAD

**Issue by robc8119** [stgeorgi/wvdquickstart#3]
One other thing I ran into for existing AD environments, the FSLogix target won't mount until you enable AD DS authentication for the storage account: https://docs.microsoft.com/en-us/azure/storage/files/storage-files-identity-ad-ds-enable. I imagine this could be automated and added to the deployment pipeline

**Comment by samvdjagt** [comment]
This is in fact part of the pipeline, the AD DS authentication is enabled for the storage account in the Cutom Scrip Extension that's run on the newly deployed VMs.
