### ISSUE TITLE
Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access

### ISSUE THREAD

**Issue by NextpointBelgium** [stgeorgi/wvdquickstart#4]
Hi,

I'm running stuck during the first run. Have disabled, CA policies, Identity Protection and revoked al authentication token and tried 2 subscription admin accounts. Every time the same error message. Executing completely empty subscription.

Any advise?

==========
Connect-AzAccount : AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'. Trace ID: 68ea69c4-9700-46ef-991b-c398615b8300 Correlation ID: 9373f28a-8e7b-4b99-9101-054e96774b03 Timestamp: 2020-08-20 20:06:22Z At line:51 char:1 + Connect-AzAccount -Environment 'AzureCloud' -Credential $AzCredential ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Connect-AzAccount], AdalClaimChallengeException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

elect-AzSubscription : Run Connect-AzAccount to login. At line:52 char:1 + Select-AzSubscription -SubscriptionId $SubscriptionId + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Set-AzContext], PSInvalidOperationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand

Time
Type
Details
8/20/2020, 10:06:22 PM
Error
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'. Trace ID: 68ea69c4-9700-46ef-991b-c398615b8300 Correlation ID: 9373f28a-8e7b-4b99-9101-054e96774b03 Timestamp: 2020-08-20 20:06:22Z
8/20/2020, 10:06:23 PM
Error
Run Connect-AzAccount to login.
8/20/2020, 10:06:24 PM
Error
Please authenticate to Azure & Azure AD using Login-AzAccount and Connect-AzureAD cmdlets and then run this script

**Comment by samvdjagt** [comment]
The solution doesn't work with accounts that have multi-factor authentication (MFA). The failure seems to indicate that MFA is still enabled for your account, as the deployment cannot authenticate with your account successfully.

**Comment by MikkoArrow** [comment]
Disable Security Defaults from your Azure AD tenant. 

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults

**Comment by NextpointBelgium** [comment]
Thank you for your help. But it's disabled already. Disable all security settings and it still fails unfortunately

**Comment by justin-shiah** [comment]
@NextpointBelgium Were you ever able to resolve this?

**Comment by NextpointBelgium** [comment]
> @NextpointBelgium Were you ever able to resolve this?

I think so. User MFA was enabled I found out. Probably this was causing issues.

**Comment by NextpointBelgium** [comment]
> > @NextpointBelgium Were you ever able to resolve this?
> 
> I think so. User MFA was enabled I found out. Probably this was causing issues.

Everything so far so good till wvd host pool deployment failed on region. :( 
> Deploy module [WvdHostPools] in [WE_WVD] via [WVDServiceConnection]

![2020-10-26 21_27_44-Pipelines - Run WVD Deployment logs and 3 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/69989491/97225236-aee8de80-17d2-11eb-9ad8-29819fc7467f.png)

**Comment by justin-shiah** [comment]
@NextpointBelgium Unfortunately we currently only support those regions specified in the error message.
